#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key=php_upload_max_filesize --value=1G
ynh_app_setting_set_default --key=php_memory_limit --value=512M
ynh_app_setting_set_default --key=php_max_execution_time --value=60

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

#ynh_setup_source --dest_dir="$install_dir"

git clone --single-branch --branch 9.1.0-build https://github.com/PrestaShop/PrestaShop.git $install_dir/PrestaShop

chown $app:www-data -R $install_dir/PrestaShop

#=================================================
# INSTALL COMPOSER
#=================================================
ynh_script_progression "Installing Composer..."

composer_version="2.9.5"

ynh_composer_install
ynh_composer_exec install --no-dev

ynh_script_progression "Create release..."
#pushd "$install_dir/PrestaShop"
#  ynh_exec_as_app php tools/build/CreateRelease.php
#popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
